trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.7.5'

stages:
  - stage: Validate
    displayName: 'Format Check & Validate'
    jobs:
      - job: Validate
        steps:
          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: $(terraformVersion)

          - script: terraform fmt -check -recursive
            displayName: 'Terraform Format Check'
            workingDirectory: '$(System.DefaultWorkingDirectory)'

          - script: |
              cd envs/dev
              terraform init -backend=false
              terraform validate
  - stage: StaticAnalysis
    displayName: 'Static Analysis'
    dependsOn: Validate
    jobs:
      - job: Lint
        steps:
          - script: |
              curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
              tflint --init
              cd envs/dev
              tflint
            displayName: 'tflint'

      - job: SecurityScan
        steps:
          - script: |
              curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
              tfsec envs/dev
            displayName: 'tfsec'

  - stage: Plan
    displayName: 'Terraform Plan'
    dependsOn: StaticAnalysis
    jobs:
      - job: Plan
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: $(terraformVersion)

          - task: TerraformTaskV4@4
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/envs/dev'
              backendServiceArm: '<your-service-connection-name>'
              backendAzureRmResourceGroupName: 'rg-terraform-state'
              backendAzureRmStorageAccountName: 'sttfstateyourinitials01'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'foundations-dev.terraform.tfstate'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/envs/dev'
              environmentServiceNameAzureRM: '<your-service-connection-name>'
              commandOptions: '-out=tfplan'

          - publish: '$(System.DefaultWorkingDirectory)/envs/dev/tfplan'
            artifact: tfplan

  - stage: Apply
    displayName: 'Terraform Apply'
    dependsOn: Plan
    jobs:
      - deployment: Apply
        environment: 'foundations-dev-approval'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: TerraformInstaller@1
                  inputs:
                    terraformVersion: $(terraformVersion)

                - download: current
                  artifact: tfplan

                - task: TerraformTaskV4@4
                  displayName: 'Terraform Init'
                  inputs:
                    provider: 'azurerm'
                    command: 'init'
                    workingDirectory: '$(System.DefaultWorkingDirectory)/envs/dev'
                    backendServiceArm: 'azure-terraform-sc'
                    backendAzureRmResourceGroupName: 'rg-terraform-state'
                    backendAzureRmStorageAccountName: 'sttffoundation2787'
                    backendAzureRmContainerName: 'tfstate'
                    backendAzureRmKey: 'foundations-dev.terraform.tfstate'

                - task: TerraformTaskV4@4
                  displayName: 'Terraform Apply'
                  inputs:
                    provider: 'azurerm'
                    command: 'apply'
                    workingDirectory: '$(System.DefaultWorkingDirectory)/envs/dev'
                    environmentServiceNameAzureRM: '<your-service-connection-name>'
                    commandOptions: '$(Pipeline.Workspace)/tfplan/tfplan'